export const translates: Record<string, Record<string, string>> = {
	'Go to homepage': {
		ua: 'Перейти на головну сторінку',
		bg: 'Към началната страница',
		hr: 'Idi na početnu stranicu',
		cs: 'Přejít na domovskou stránku',
		da: 'Gå til forsiden',
		nl: 'Ga naar de homepage',
		en: 'Go to homepage',
		et: 'Mine avalehele',
		fi: 'Siirry etusivulle',
		fr: "Aller à la page d'accueil",
		de: 'Zur Startseite',
		el: 'Μετάβαση στην αρχική σελίδα',
		hu: 'Ugrás a kezdőlapra',
		ga: 'Téigh go dtí an leathanach baile',
		it: 'Vai alla home page',
		lv: 'Doties uz sākumlapu',
		lt: 'Eiti į pagrindinį puslapį',
		mt: 'Mur fil-paġna ewlenija',
		pl: 'Przejdź do strony głównej',
		pt: 'Ir para a página inicial',
		ro: 'Mergi la pagina principală',
		sk: 'Prejsť na domovskú stránku',
		sl: 'Pojdi na domačo stran',
		es: 'Ir a la página de inicio',
		sv: 'Gå till startsidan',
	},
	'Switch to dark mode': {
		ua: 'Увімкнути темний режим',
		bg: 'Превключване към тъмен режим',
		hr: 'Prebaci na tamni način rada',
		cs: 'Přepnout do tmavého režimu',
		da: 'Skift til mørk tilstand',
		nl: 'Schakel naar donkere modus',
		en: 'Switch to dark mode',
		et: 'Lülitu tumedale režiimile',
		fi: 'Vaihda tummaan tilaan',
		fr: 'Passer en mode sombre',
		de: 'In den Dunkelmodus wechseln',
		el: 'Μετάβαση σε σκοτεινή λειτουργία',
		hu: 'Váltás sötét módra',
		ga: 'Athraigh go mód dorcha',
		it: 'Passa alla modalità scura',
		lv: 'Pārslēgt uz tumšo režīmu',
		lt: 'Perjungti į tamsųjį režimą',
		mt: 'Aqleb għall-modalità skura',
		pl: 'Przełącz na tryb ciemny',
		pt: 'Mudar para o modo escuro',
		ro: 'Comută la modul întunecat',
		sk: 'Prepnúť do tmavého režimu',
		sl: 'Preklopi v temni način',
		es: 'Cambiar a modo oscuro',
		sv: 'Byt till mörkt läge',
	},
	'Switch to light mode': {
		ua: 'Увімкнути світлий режим',
		bg: 'Превключване към светъл режим',
		hr: 'Prebaci na svijetli način rada',
		cs: 'Přepnout do světlého režimu',
		da: 'Skift til lys tilstand',
		nl: 'Schakel naar lichte modus',
		en: 'Switch to light mode',
		et: 'Lülitu heledale režiimile',
		fi: 'Vaihda vaaleaan tilaan',
		fr: 'Passer en mode clair',
		de: 'In den Hellmodus wechseln',
		el: 'Μετάβαση σε φωτεινή λειτουργία',
		hu: 'Váltás világos módra',
		ga: 'Athraigh go mód geal',
		it: 'Passa alla modalità chiara',
		lv: 'Pārslēgt uz gaišo režīmu',
		lt: 'Perjungti į šviesųjį režimą',
		mt: 'Aqleb għall-modalità ċara',
		pl: 'Przełącz na tryb jasny',
		pt: 'Mudar para o modo claro',
		ro: 'Comută la modul luminos',
		sk: 'Prepnúť do svetlého režimu',
		sl: 'Preklopi v svetli način',
		es: 'Cambiar a modo claro',
		sv: 'Byt till ljust läge',
	},
	'Open language menu': {
		ua: 'Відкрити меню мов',
		bg: 'Отваряне на менюто за езици',
		hr: 'Otvori izbornik jezika',
		cs: 'Otevřít nabídku jazyků',
		da: 'Åbn sprogmenuen',
		nl: 'Taalmenu openen',
		en: 'Open language menu',
		et: 'Ava keelemenüü',
		fi: 'Avaa kielivalikko',
		fr: 'Ouvrir le menu des langues',
		de: 'Sprachmenü öffnen',
		el: 'Άνοιγμα μενού γλωσσών',
		hu: 'Nyelvi menü megnyitása',
		ga: 'Oscail roghchlár teanga',
		it: 'Apri il menu delle lingue',
		lv: 'Atvērt valodu izvēlni',
		lt: 'Atidaryti kalbų meniu',
		mt: 'Iftaħ il-menu tal-lingwi',
		pl: 'Otwórz menu języków',
		pt: 'Abrir menu de idiomas',
		ro: 'Deschide meniul de limbi',
		sk: 'Otvoriť ponuku jazykov',
		sl: 'Odpri meni jezikov',
		es: 'Abrir menú de idiomas',
		sv: 'Öppna språkmenyn',
	},
	'Switch language to': {
		ua: 'Перемкнути мову на',
		bg: 'Превключване на езика на',
		hr: 'Promijeni jezik na',
		cs: 'Přepnout jazyk na',
		da: 'Skift sprog til',
		nl: 'Taal wijzigen naar',
		en: 'Switch language to',
		et: 'Vaheta keel keeleks',
		fi: 'Vaihda kieleksi',
		fr: 'Passer la langue à',
		de: 'Sprache umstellen auf',
		el: 'Αλλαγή γλώσσας σε',
		hu: 'Nyelv váltása erre',
		ga: 'Athraigh an teanga go',
		it: 'Cambia lingua in',
		lv: 'Pārslēgt valodu uz',
		lt: 'Perjungti kalbą į',
		mt: 'Aqleb il-lingwa għal',
		pl: 'Przełącz język na',
		pt: 'Mudar idioma para',
		ro: 'Schimbă limba în',
		sk: 'Prepnúť jazyk na',
		sl: 'Preklopi jezik na',
		es: 'Cambiar idioma a',
		sv: 'Byt språk till',
	},
};
